# Generated by Django 4.0.6 on 2023-02-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
        ('students', '0002_eei_sponsorstudent_remove_sponsors_spent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorstudent',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.sponsors'),
        ),
        migrations.AlterField(
            model_name='students',
            name='sponsor',
            field=models.ManyToManyField(related_name='student', through='students.SponsorStudent', to='sponsors.sponsors'),
        ),
        migrations.DeleteModel(
            name='Sponsors',
        ),
    ]
