# Generated by Django 4.0.6 on 2023-02-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='type',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='sponsor',
            new_name='sponsors',
        ),
    ]
