# Generated by Django 4.0.6 on 2023-02-05 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_type_students_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
