# Generated by Django 4.1.6 on 2023-02-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_rename_organiztion_name_sponsors_organization_name'),
        ('students', '0006_students_reg_date_students_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorstudent',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studentsponsor', to='sponsors.sponsors'),
        ),
        migrations.AlterField(
            model_name='sponsorstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studentsponsor', to='students.students'),
        ),
    ]
