# Generated by Django 4.1.6 on 2023-02-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_rename_organiztion_name_sponsors_organization_name'),
        ('students', '0007_alter_sponsorstudent_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorstudent',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorstudent', to='sponsors.sponsors'),
        ),
    ]
