# Generated by Django 4.0.6 on 2023-02-01 09:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('sponsorship_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('New', 'New'), ('Checking', 'Checking'), ('Verifayed', 'Verifayed'), ('Denied', 'Denied')], default='New', max_length=9)),
                ('is_organization', models.BooleanField(default=False)),
                ('organiztion_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
