# Generated by Django 4.0.6 on 2023-02-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='organiztion_name',
        ),
    ]
