# Generated by Django 4.0.6 on 2023-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_remove_sponsors_organiztion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='organiztion_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
