# Generated by Django 4.0.6 on 2023-02-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_sponsors_organiztion_name_alter_sponsors_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
