# Generated by Django 4.1.6 on 2023-02-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_sponsors_updated_time_alter_sponsors_reg_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsors',
            old_name='organiztion_name',
            new_name='organization_name',
        ),
    ]
